[package]
name = "pokemon-tcg-pocket-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
csv = "1.3.1"
serde = { version = "1.0.218", features = ["derive"] }
toml = "0.8.20"
